
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Aug 08 14:12:32 CEST 2019
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TK_RPAREN = 9;
  public static final int TK_DIV = 4;
  public static final int TK_LPAREN = 8;
  public static final int TK_VAL = 10;
  public static final int EOF = 0;
  public static final int TK_MULT = 3;
  public static final int TK_DONE = 7;
  public static final int TK_POW = 6;
  public static final int error = 1;
  public static final int TK_PLUS = 2;
  public static final int TK_MINUS = 5;
}

